- name: Demo on vars
  hosts: all
  vars:
    action: false
  tasks:
      - name: Printing DiMy D0 Distro is centos
        ansible.builtin.debug:
          msg: My D0 Distro is {{ansible_distribution}}
        when: ansible_distribution == "centos"

      - name: Printing DiMy D0 Distro is Ubuntu
        ansible.builtin.debug:
          msg: My D0 Distro is {{ansible_distribution}}
        when: ansible_distribution == "ubuntu"


      - name: Run this action
        ansible.builtin.debug:
          msg: Action is defined
        when: action
