- name: Demo on using loops  
  hosts: all
  tasks:
      - name: Demo on Loops
      ansible.builtin.debug:
        msg: "value is: {{item}}" #item is the keyword to represent the element in the loop
      loop:
        - 10
        - 20
        - 30