- name: Demo of installing the packages
  hosts: all
  become: yes
  tasks:
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: present


  - name: Install the latest version of wget and jq
    ansible.builtin.package:
      name:
        - wget
        - jq
      state: latest