- name: Configuring the service
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Restarting {{COMPONENT}}
  ansible.builtin.service:
    state: restarted
    name: "{{COMPONENT}}"
    enabled: yes
    

